ServerEvents.recipes(e =>{
    e.remove({output:'computercraft:cable'})
    e.remove({output:'computercraft:computer_normal'})
    e.remove({output:'computercraft:computer_advanced'})
    e.remove({output:'computercraft:monitor_normal'})
    e.remove({output:'computercraft:monitor_advanced'})
    e.shaped('computercraft:cable',[
        ' I ',
        'IFI',
        ' I '
    ],{
        I:'createdeco:industrial_iron_sheet',
        F:'ae2:black_glass_cable'
    })
    e.recipes.create.mechanical_crafting('computercraft:computer_normal',
        [
            'III',
            'MKI',
            'III'
        ],{
            I:'createdeco:industrial_iron_sheet',
            M:'computercraft:monitor_normal',
            K:'create_dd:kinetic_mechanism'
        }
    )
    e.recipes.create.mechanical_crafting('computercraft:computer_advanced',
        [
            'GGGGG',
            'GEVEG',
            'GMCFG',
            'GELEG',
            'GGGGG'
        ],{
            G:'create_new_age:overcharged_golden_sheet',
            E:'createaddition:electrum_sheet',
            V:'create_things_and_misc:vibration_mechanism',
            M:'computercraft:monitor_advanced',
            C:'computercraft:computer_normal',
            F:'computercraft:cable',
            L:'ae2:logic_processor'
        }
    )
    e.recipes.create.mechanical_crafting('computercraft:monitor_normal',
        [
            'III',
            'TPI',
            'III'
        ],{
            I:'createdeco:industrial_iron_sheet',
            T:'minecraft:tinted_glass',
            P:'ae2:dark_monitor'
        })
    e.recipes.create.mechanical_crafting('computercraft:monitor_advanced',
        [
            'GGG',
            'MAG',
            'GGG'
        ],{
            G:'create_new_age:overcharged_golden_sheet',
            M:'computercraft:monitor_normal',
            A:'advancedperipherals:weak_automata_core'
        }
    )
})