ServerEvents.recipes(e => {
    e.recipes.createMechanicalExtruderExtruding(
        Item.of('minecraft:calcite'),
        [
            Fluid.of('garnished:garnish'),
            Fluid.of('minecraft:lava')
        ]
    )
    e.recipes.createMechanicalExtruderExtruding(
        Item.of('create:ochrum'),
        [
            Fluid.of('garnished:apple_cider'),
            Fluid.of('minecraft:lava')
        ]
    )
    e.recipes.createMechanicalExtruderExtruding(
        Item.of('minecraft:dripstone_block'),
        [
            Fluid.of('garnished:peanut_oil'),
            Fluid.of('minecraft:lava')
        ]
    )
    e.recipes.createMechanicalExtruderExtruding(
        Item.of('minecraft:end_stone'),
        [
            Fluid.of('garnished:cashew_mixture'),
            Fluid.of('minecraft:lava')
        ]
    )
    e.recipes.createMechanicalExtruderExtruding(
        Item.of('minecraft:tuff'),
        [
            Fluid.of('garnished:mastic_resin'),
            Fluid.of('minecraft:lava')
        ]
    )
    e.recipes.createMechanicalExtruderExtruding(
        Item.of('create:crimsite'),
        [
            Fluid.of('garnished:red_mastic_resin'),
            Fluid.of('minecraft:lava')
        ]
    )
    e.recipes.createMechanicalExtruderExtruding(
        Item.of('garnished:ritualistic_stone'),
        [
            Fluid.of('garnished:orange_mastic_resin'),
            Fluid.of('minecraft:lava')
        ]
    )
    e.recipes.createMechanicalExtruderExtruding(
        Item.of('garnished:carnotite'),
        [
            Fluid.of('garnished:yellow_mastic_resin'),
            Fluid.of('minecraft:lava')
        ]
    )
    e.recipes.createMechanicalExtruderExtruding(
        Item.of('create:veridium'),
        [
            Fluid.of('garnished:green_mastic_resin'),
            Fluid.of('minecraft:lava')
        ]
    )
    e.recipes.createMechanicalExtruderExtruding(
        Item.of('create:asurine'),
        [
            Fluid.of('garnished:blue_mastic_resin'),
            Fluid.of('minecraft:lava')
        ]
    )
    e.recipes.createMechanicalExtruderExtruding(
        Item.of('garnished:abyssal_stone'),
        [
            Fluid.of('garnished:purple_mastic_resin'),
            Fluid.of('minecraft:lava')
        ]
    )
    e.recipes.createMechanicalExtruderExtruding(
        Item.of('tfmg:bauxite'),
        [

            Fluid.of('minecraft:lava'),
            Item.of('geode_plus:pink_topaz_block')
        ]
    )
})