StartupEvents.registry('item', e =>{
    e.create('enstatite')
    e.create('forsterite')
    e.create('polished_mana_diamond')
    e.create('mana_tube')
    e.create('terrasteel_sheet')
    e.create('polished_mana_quartz')
    e.create('polished_elven_quartz')
    e.create('polished_dragonstone')
    e.create('manasteel_sheet')
    e.create('manasteel_rod')
    e.create('manasteel_spring')
    e.create('manasteel_ring')
    e.create('manasteel_large_ring')
    e.create('incomplete_printed_accumulation_circuit')
    e.create('incomplete_printed_accumulation_processor').texture('megacells:accumulation_processor')
})